#!/usr/bin/env node
/**
 * sync-to-java.mjs
 *
 * Reads the TypeScript game engine source (constants.ts + levels.ts) and
 * regenerates the corresponding Java source files, then rebuilds the WAR.
 *
 * Usage:  node scripts/src/sync-to-java.mjs
 *
 * What it syncs:
 *  1. constants.ts  →  GameConstants.java (new file) +
 *                      GameWorld.java (GRID_W, GRID_H, TICK_RATE_MS, etc.)
 *  2. levels.ts     →  LevelDesigner.java (all 10 level obstacle definitions)
 *
 * The script uses regex-based extraction — the source files must keep the
 * well-defined constant blocks and LEVELS array format produced by constants.ts
 * and levels.ts.
 */

import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dir     = dirname(__filename);
const ROOT      = resolve(__dir, "../..");
const TS_GAME   = resolve(ROOT, "artifacts/api-server/src/game");
const JAVA_SRC  = resolve(ROOT, "artifacts/snake-game/src/main/java/com/snakegame/game");
const POM       = resolve(ROOT, "artifacts/snake-game/pom.xml");

// ─────────────────────────────────────────────────────────────────────────────
// 1. Parse constants.ts
// ─────────────────────────────────────────────────────────────────────────────

function parseConstants(src) {
  const extract = (name) => {
    const m = src.match(new RegExp(`export const ${name}\\s*=\\s*([\\d.]+)`));
    return m ? Number(m[1]) : null;
  };
  return {
    GRID_W:                  extract("GRID_W"),
    GRID_H:                  extract("GRID_H"),
    MAX_PLAYERS:             extract("MAX_PLAYERS"),
    MAX_APPLES:              extract("MAX_APPLES"),
    TOTAL_LEVELS:            extract("TOTAL_LEVELS"),
    TICK_RATE_MS:            extract("TICK_RATE_MS"),
    DOUBLE_TAP_THRESHOLD_MS: extract("DOUBLE_TAP_THRESHOLD_MS"),
    LEVEL_PAUSE_MS:          extract("LEVEL_PAUSE_MS"),
    SCORE_PER_APPLE_PER_LEVEL: extract("SCORE_PER_APPLE_PER_LEVEL"),
    LEVEL_UP_THRESHOLD:      extract("LEVEL_UP_THRESHOLD"),
    INITIAL_SNAKE_LENGTH:    extract("INITIAL_SNAKE_LENGTH"),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Parse levels.ts → extract obstacle definitions per level
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Very simplified level extractor.
 * Evaluates the LEVELS array by spinning up a stripped version via Node.
 * The levels.ts file imports GRID_W / GRID_H from constants — we rewrite
 * those imports inline before eval.
 */
async function parseLevels(constantsSrc, levelsSrc, consts) {
  // Replace ES-module imports with hardcoded constants inline
  let evalSrc = levelsSrc
    .replace(/^import\s.*?from.*?;?\s*$/gm, "")
    .replace(/^export type\s.*?;?\s*$/gm, "")
    .replace(/^export interface.*?\{[\s\S]*?\}\s*$/gm, "")
    .replace(/\bGRID_W\b/g, String(consts.GRID_W))
    .replace(/\bGRID_H\b/g, String(consts.GRID_H));

  // Inject helper constants so the spread operator IIFE etc work fine
  const preamble = `
const __levels = [];
function hwall(x1,x2,y) { const p=[]; for(let x=Math.min(x1,x2);x<=Math.max(x1,x2);x++) p.push({x,y}); return p; }
function vwall(x,y1,y2) { const p=[]; for(let y=Math.min(y1,y2);y<=Math.max(y1,y2);y++) p.push({x,y}); return p; }
function block(x1,y1,x2,y2) { const p=[]; for(let y=y1;y<=y2;y++) for(let x=x1;x<=x2;x++) p.push({x,y}); return p; }
function row(sx,y,len) { const p=[]; for(let i=0;i<len;i++) p.push({x:sx+i,y}); return p; }
function col(x,sy,len) { const p=[]; for(let i=0;i<len;i++) p.push({x,y:sy+i}); return p; }
`;

  // Extract LEVELS array text
  const levelsMatch = evalSrc.match(/export const LEVELS[\s\S]*?= \[([\s\S]*)\];/);
  if (!levelsMatch) {
    throw new Error("Could not find LEVELS array in levels.ts");
  }
  const arrayBody = levelsMatch[1];

  const script = preamble + `\nconst LEVELS = [${arrayBody}];\nLEVELS;`;
  const { default: vm } = await import("vm");
  const ctx = vm.createContext({ Math, Date, console });
  const result = vm.runInContext(script, ctx);
  return result; // JS array of LevelDef[]
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. Generate Java GameConstants.java
// ─────────────────────────────────────────────────────────────────────────────

function generateGameConstants(consts) {
  return `package com.snakegame.game;

/**
 * Auto-generated by sync-to-java.mjs from artifacts/api-server/src/game/constants.ts
 * Do not edit manually — run the sync script instead.
 */
public final class GameConstants {
    private GameConstants() {}

    public static final int    GRID_W                    = ${consts.GRID_W};
    public static final int    GRID_H                    = ${consts.GRID_H};
    public static final int    MAX_PLAYERS               = ${consts.MAX_PLAYERS};
    public static final int    MAX_APPLES                = ${consts.MAX_APPLES};
    public static final int    TOTAL_LEVELS              = ${consts.TOTAL_LEVELS};
    public static final long   TICK_RATE_MS              = ${consts.TICK_RATE_MS};
    public static final long   DOUBLE_TAP_THRESHOLD_MS   = ${consts.DOUBLE_TAP_THRESHOLD_MS};
    public static final long   LEVEL_PAUSE_MS            = ${consts.LEVEL_PAUSE_MS};
    public static final int    SCORE_PER_APPLE_PER_LEVEL = ${consts.SCORE_PER_APPLE_PER_LEVEL};
    public static final int    LEVEL_UP_THRESHOLD        = ${consts.LEVEL_UP_THRESHOLD};
    public static final int    INITIAL_SNAKE_LENGTH      = ${consts.INITIAL_SNAKE_LENGTH};
}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Generate Java LevelDesigner.java
// ─────────────────────────────────────────────────────────────────────────────

function ptToJava(pt) {
  return `new Point(${pt.x}, ${pt.y})`;
}

function obstacleToJava(obs, indent = "            ") {
  const cellsJava = obs.cells.map(ptToJava).join(`,\n${indent}    `);
  if (obs.type === "WALL") {
    return `${indent}addWall(obstacles, new Point[]{\n${indent}    ${cellsJava}\n${indent}});`;
  }
  const dir = obs.dir ?? "RIGHT";
  const interval = obs.interval ?? 5;
  return `${indent}addMovingBlock(obstacles, new Point[]{\n${indent}    ${cellsJava}\n${indent}}, Direction.${dir}, ${interval});`;
}

function generateLevelDesigner(levels) {
  const levelMethods = levels.map((level, i) => {
    const num = i + 1;
    const lines = level.map((obs) => obstacleToJava(obs));
    return `    private static List<Obstacle> level${num}() {
        List<Obstacle> obstacles = new ArrayList<>();
${lines.join("\n")}
        return obstacles;
    }`;
  });

  return `package com.snakegame.game;

import java.awt.Point;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Auto-generated by sync-to-java.mjs from artifacts/api-server/src/game/levels.ts
 * Do not edit manually — run the sync script instead.
 */
public final class LevelDesigner {
    private LevelDesigner() {}

    public static List<Obstacle> getLevel(int level) {
        switch (level) {
${levels.map((_, i) => `            case ${i + 1}: return level${i + 1}();`).join("\n")}
            default: return new ArrayList<>();
        }
    }

${levelMethods.join("\n\n")}

    // ── helpers ─────────────────────────────────────────────────────────────

    private static void addWall(List<Obstacle> obs, Point[] cells) {
        obs.add(new Obstacle(Obstacle.Type.WALL, Arrays.asList(cells), null, 0));
    }

    private static void addMovingBlock(List<Obstacle> obs, Point[] cells,
            Direction dir, int interval) {
        obs.add(new Obstacle(Obstacle.Type.MOVING_BLOCK, Arrays.asList(cells), dir, interval));
    }
}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. Patch GameWorld.java constants
// ─────────────────────────────────────────────────────────────────────────────

function patchGameWorld(src, consts) {
  const replacements = {
    GRID_W:          consts.GRID_W,
    GRID_H:          consts.GRID_H,
    MAX_PLAYERS:     consts.MAX_PLAYERS,
    MAX_APPLES:      consts.MAX_APPLES,
    TOTAL_LEVELS:    consts.TOTAL_LEVELS,
    TICK_RATE_MS:    consts.TICK_RATE_MS,
    LEVEL_UP_THRESHOLD: consts.LEVEL_UP_THRESHOLD,
  };
  let out = src;
  for (const [name, val] of Object.entries(replacements)) {
    // Match: private static final int GRID_W = 40;
    //  or:   private static final long TICK_RATE_MS = 100;
    out = out.replace(
      new RegExp(`(private static final \\w+ ${name}\\s*=\\s*)[\\d.]+`),
      `$1${val}`,
    );
  }
  return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. Main
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log("=== sync-to-java.mjs ===\n");

  // --- Read sources ---
  const constantsSrc = readFileSync(resolve(TS_GAME, "constants.ts"), "utf8");
  const levelsSrc    = readFileSync(resolve(TS_GAME, "levels.ts"),    "utf8");

  // --- Parse ---
  console.log("Parsing constants.ts …");
  const consts = parseConstants(constantsSrc);
  Object.entries(consts).forEach(([k, v]) => console.log(`  ${k} = ${v}`));

  console.log("\nParsing levels.ts …");
  const levels = await parseLevels(constantsSrc, levelsSrc, consts);
  levels.forEach((level, i) => {
    console.log(`  Level ${i + 1}: ${level.length} obstacle(s)`);
  });

  // --- Generate GameConstants.java ---
  const gcPath = resolve(JAVA_SRC, "GameConstants.java");
  const gcJava = generateGameConstants(consts);
  writeFileSync(gcPath, gcJava, "utf8");
  console.log(`\nWrote ${gcPath}`);

  // --- Generate LevelDesigner.java ---
  const ldPath = resolve(JAVA_SRC, "LevelDesigner.java");
  const ldJava = generateLevelDesigner(levels);
  writeFileSync(ldPath, ldJava, "utf8");
  console.log(`Wrote ${ldPath}`);

  // --- Patch GameWorld.java ---
  const gwPath = resolve(JAVA_SRC, "GameWorld.java");
  let gwSrc;
  try { gwSrc = readFileSync(gwPath, "utf8"); }
  catch { console.warn("  Warning: GameWorld.java not found, skipping patch."); gwSrc = null; }
  if (gwSrc) {
    const patched = patchGameWorld(gwSrc, consts);
    if (patched !== gwSrc) {
      writeFileSync(gwPath, patched, "utf8");
      console.log(`Patched ${gwPath}`);
    } else {
      console.log(`${gwPath} — no changes needed`);
    }
  }

  // --- Rebuild WAR ---
  console.log("\nRebuilding WAR (mvn package -DskipTests) …");
  try {
    execSync("mvn package -DskipTests -q", {
      cwd: resolve(ROOT, "artifacts/snake-game"),
      stdio: "inherit",
    });
    console.log("WAR rebuilt successfully.");
  } catch (err) {
    console.error("Maven build failed. Java/Maven may not be installed in this environment.");
    console.error("Run the script on a machine with Java 8 + Maven 3 to build the WAR.");
    process.exit(1);
  }

  console.log("\n=== Done ===");
}

main().catch((err) => { console.error(err); process.exit(1); });
